### ISSUE TITLE
Cannot install via easy_install

### ISSUE THREAD

**Issue by MikeVL** [agschwender/pilbox#31]
root@698a4fd0d906:/# easy_install -UZ pilbox
Searching for pilbox
Reading https://pypi.python.org/simple/pilbox/
Best match: pilbox 1.1.6.linux-x86-64
Downloading https://pypi.python.org/packages/any/p/pilbox/pilbox-1.1.6.linux-x86_64.tar.gz#md5=487ee2bbd66ec6a59b055bfdc41ac1a8
Processing pilbox-1.1.6.linux-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-cib_xgi4/pilbox-1.1.6.linux-x86_64.tar.gz

**Comment by agschwender** [comment]
Removed the binary distribution for linux. Should correct the problem.
