### ISSUE TITLE
Preserving Exif information

### ISSUE THREAD

**Issue by devoto13** [agschwender/pilbox#36]
Hi!

This issue somehow connected with #24. Visible effect is that image is rotated after processing. Basically the problem comes from Pillow, which removes all Exif information on save. I saw issue was addressed by adding `rotate="auto"` in version 1.1.1.

For my use case I would prefer to keep Exif information including Orientation tag in resized image instead of rotating image and removing all the information. It's possible according to python-pillow/Pillow#183. 

So the idea is to add another option for Pilbox (`preserve_exif` for example) and keep this information in processed image. Do you have any thoughts on this topic? Will it be merged if I provide a pull-request?

**Comment by agschwender** [comment]
Sure, that seems reasonable.
