### ISSUE TITLE
security issue - cannot validate signature

### ISSUE THREAD

**Issue by pythonishvili** [agschwender/pilbox#39]
Assume I start the server with:
`python -m pilbox.app --client_key=dupa`

Then I launch some operation like this:
`http://localhost:8888/?url=some.jpg&w=500&h=500&sig=dupa`

I get:
`{"status_code": 403, "error_code": 101, "error": "Invalid signature"}`

I wonder what I might be doing wrong. I tried to investigate the source code and:
`self.settings.get("client_key") is 'dupa'`

but
`verify_signature(key, urlparse(self.request.uri).query) is False`

`qs == 'url=some.jpg&w=500&h=500&sig=dupa'`
`unsigned_qs == 'url=some.jpg&w=500&h=500'`

this produces some kind of a hash
`sig = derive_signature(key, unsigned_qs)  # like 'b4805a1b12a0aeb3fb8e2c7e9c435bd3f3a4088a'`

and the final comparison:
`urlparse.parse_qs(qs).get("sig", [None])[0] == sig`
is always False because
`urlparse.parse_qs(qs).get("sig", [None])[0] is 'dupa'`
while
`sig is  'b4805a1b12a0aeb3fb8e2c7e9c435bd3f3a4088a'`

**Comment by agschwender** [comment]
The `client_key` is used to sign the query string, but it is not itself the `sig` value. For example, 

```
$ python -m pilbox.signature --key=abcdef "x=1&y=2&z=3"
Query String: x=1&y=2&z=3
Signature: c9516346abf62876b6345817dba2f9a0c797ef26
Signed Query String: x=1&y=2&z=3&sig=c9516346abf62876b6345817dba2f9a0c797ef26
```

A `client_key` of `abcdef` produces a signature value of `c9516346abf62876b6345817dba2f9a0c797ef26` for the query string `x=1&y=2&z=3`. Please, refer to the [Signing](https://github.com/agschwender/pilbox#signing) section for more details about signing your requests.

**Comment by pythonishvili** [comment]
Thanks, now it's clear.
