### ISSUE TITLE
Make benefit of PycURL more clear

### ISSUE THREAD

**Issue by Tenzer** [agschwender/pilbox#40]
Thanks for a nice project!

When trying to set it up and test it, I found that Pilbox couldn't fetch images from upstream HTTPS servers which only supports TLS and not SSL - this is for instance the case for sites which use AWS CloudFront with HTTPS, but doesn't the extra premium to get dedicated IP addresses for the site.
Such errors give a stack trace ending with:

    SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

It can be solved by installing PycURL, but perhaps that should be made more clear? I have a feeling that SSL slowly will die out and more and more people will experience this problem, so perhaps a note in the README file or even a warning on start up would be a good idea?

**Comment by agschwender** [comment]
That's good advice. Will try to update the README this weekend.

**Comment by agschwender** [comment]
Not sure if it really hits the reader over the head, but I added a recommendation for installing pycurl.

**Comment by Tenzer** [comment]
It's at least better than before. Thanks! :)
