### ISSUE TITLE
animated gif support

### ISSUE THREAD

**Issue by phoet** [agschwender/pilbox#41]
hi there,

i can't find anything related to supporting animated gifs (try [this link as an example](https://jimdo-pilbox.herokuapp.com/?w=400&url=http://u.jimdo.com/www400/o/s2fae6fd28c99cb5f/img/i32d3f6f66d676d8b/1433149908/std/image.gif)).

the first frame of the gif is handled fine, maybe that's on purpose, but i would like to resize, crop etc all the frames and get back the original gif animation. as far as [i can see](https://github.com/python-pillow/Pillow/blob/master/Scripts/gifmaker.py) pillow supports animated gif handling.

is this something you would like to support in pilbox?

all feedback appreciated!

/cc @seichner

**Comment by agschwender** [comment]
I've considered this. My main concern is that I can't imagine that this will ever be fast enough to allow "realtime" resizing. The files themselves tend to be large and would require long download times, and resizing all those frames will be time consuming itself. If it were a one-liner, I'd probably implement it and leave it to the caller to determine if it was acceptable or not, but I suspect it'd be a bit more work than that. That said, it's possible that I'm completely wrong, but I would like to see a bit of demand to determine if it's worth putting the effort in.

**Comment by phoet** [comment]
thanks for your feedback @agschwender 

we are currently evaluating some image services at jimdo and need to match our existing feature-set. unfortunately resizing of animated gifs is one of them :smile_cat: and services like [thumbor](https://github.com/thumbor/thumbor) allow exactly that.

if you can give me some starting points, i would be happy to spike a solution with my unbearable python skills.

**Comment by agschwender** [comment]
I look at thumbor as sort of a superset of everything that anyone has ever needed for image resizing. With pilbox, I've tried to take a more minimal approach which I believe lends itself to more readable code and less dependencies. So I'm happy to have a smaller feature set, that satisfies most use cases and let users which require a larger feature set use other services. That said, if there was a ton of demand for this feature among pilbox's user base or if the code/dependency changes were so minimal that it wouldn't be burdensome to add/maintain, I'd re-evaluate its inclusion.

**Comment by phoet** [comment]
i like your thinking. nevertheless, i'll try to polish my python coding and see if i can get a working prototype so we have something to base the burdensomeness on

**Comment by elpollodiablo** [comment]
Did you make any progress in this @phoet?

**Comment by phoet** [comment]
We discontinued this path as animated gif support in pil is quite poor. We are now using gifsicle in thumbor for this purpose. Thx for your feedback and support.
