### ISSUE TITLE
Spaces in upstream URLs

### ISSUE THREAD

**Issue by Tenzer** [agschwender/pilbox#42]
Hi

It seems like there's a problem with the encoding of upstream URLs when they contain spaces. This is however only a problem with some upstreams - I am seeing it with S3 but not with Nginx. I have found numerous mentions of this problem specifically with S3, and there's even a [forum thread](https://forums.aws.amazon.com/message.jspa?messageID=39255) from 2006 which mentions this problem.

The problem only seems to relate to spaces due to how the headers are sent over HTTP. I have put up a test file on S3 and did a quick test via curl. curl doesn't do the URL encoding by itself, so it is good for testing this with. Here's a test with a normal space in the URL:

```bash
$ curl --head --verbose 'http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png'
*   Trying 54.231.130.139...
* Connected to pilbox-space-test.s3-eu-west-1.amazonaws.com (54.231.130.139) port 80 (#0)
> HEAD /test image.png HTTP/1.1
> Host: pilbox-space-test.s3-eu-west-1.amazonaws.com
> User-Agent: curl/7.42.1
> Accept: */*
>
< HTTP/1.1 505 HTTP Version not supported
HTTP/1.1 505 HTTP Version not supported
< Date: Mon, 01 Jun 15 14:04:54 GMT
Date: Mon, 01 Jun 15 14:04:54 GMT
< Connection: close
Connection: close
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< x-amz-id-2: gy/LaxRfoO5dF6Kxz7B8VOcWoTVIYNZXoZorJPHuJiAjJ94mQHkGz+OfRvIXlq0IaDBR71E18Z7O9Dp3lg/TwoLyxfeGk81t
x-amz-id-2: gy/LaxRfoO5dF6Kxz7B8VOcWoTVIYNZXoZorJPHuJiAjJ94mQHkGz+OfRvIXlq0IaDBR71E18Z7O9Dp3lg/TwoLyxfeGk81t
< x-amz-request-id: 872E7839A03D35F
x-amz-request-id: 872E7839A03D35F
< Content-Type: application/xml
Content-Type: application/xml

<
* Excess found in a non pipelined read: excess = 315 url = /test image.png (zero-length body)
* Closing connection 0
```

And here's where I have replaced the space with `%20`:

```bash
$ curl --head --verbose 'http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test%20image.png'
*   Trying 54.231.130.139...
* Connected to pilbox-space-test.s3-eu-west-1.amazonaws.com (54.231.130.139) port 80 (#0)
> HEAD /test%20image.png HTTP/1.1
> Host: pilbox-space-test.s3-eu-west-1.amazonaws.com
> User-Agent: curl/7.42.1
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< x-amz-id-2: hKoX6GPzBlfa9SP6AEUpPxaA5l+GfwEBY+J5+Zc/Xo71SAG7vr+YseDieuFGohauCEFcG9GDvv8=
x-amz-id-2: hKoX6GPzBlfa9SP6AEUpPxaA5l+GfwEBY+J5+Zc/Xo71SAG7vr+YseDieuFGohauCEFcG9GDvv8=
< x-amz-request-id: 4A03CDDAB70A708B
x-amz-request-id: 4A03CDDAB70A708B
< Date: Mon, 01 Jun 2015 14:05:44 GMT
Date: Mon, 01 Jun 2015 14:05:44 GMT
< Last-Modified: Mon, 01 Jun 2015 13:57:58 GMT
Last-Modified: Mon, 01 Jun 2015 13:57:58 GMT
< ETag: "814a0034f5549e957ee61360d87457e5"
ETag: "814a0034f5549e957ee61360d87457e5"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Type: image/png
Content-Type: image/png
< Content-Length: 473831
Content-Length: 473831
< Server: AmazonS3
Server: AmazonS3

<
* Connection #0 to host pilbox-space-test.s3-eu-west-1.amazonaws.com left intact
```

The difference can be see in the `HEAD` line where the space in the file name presumably give problems with the parsing of the headers on the S3 end, and they assume "image.png" is a HTTP version.

I have done some testing of Pilbox in relation to this, and it seems like it always sends an literal space character to the upstream, even though it is sent %20. Do you want me to make a patch for replacing spaces with %20 before doing the upstream requests?

**Comment by agschwender** [comment]
I'm not able to reproduce by adding a `test space.jpg` file in my test cases. So I _believe_ this may be more a client encoding problem or a server response problem.

If I want to request a resize for this url:

`http://example.org/test image.jpg`

I'd need to send it as:

`http://localhost:8000/?url=http%3A%2F%2Fexample.org%2Ftest%20image.jpg`

But if I want to request a resize for this url:

`http://example.org/test%20image.jpg`

I'd need to send it as:

`http://localhost:8000/?url=http%3A%2F%2Fexample.org%2Ftest%2520image.jpg`

In any case, a space is considered an unsafe character and should always be url encoded according to the [URL RFC](http://www.ietf.org/rfc/rfc1738.txt). If I'm misunderstanding what you're saying though, I'm happy to look into it more.

**Comment by Tenzer** [comment]
First of, I have only seen this problem when accessing files from S3, as they seem to be more strict with parsing the request headers, so if you don't test against S3 you will likely not see the problem. You can use this image as a test target: [http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png](http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png).

Thinking a bit about it, it makes sense that Pilbox would require the URL to be encoded (actually double encoded, depending on how you look at it), we have however made a wrapper for Pilbox based on the [example on the website](http://agschwender.github.io/pilbox/#extension), where everything following the dimensions are regarded as the URL. In the application where we call Pilbox we do however not use any explicit URL encoding, which causes a problem when the URL contains unsafe characters. I have worked around it now by encoding the URL before handing it over to Pilbox and it seems to work.

I don't know if the example was intended to be used the same way, ie. where you can call Pilbox with a URL such as [http://127.0.0.1:8888/100x100/http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png](http://127.0.0.1:8888/100x100/http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png), otherwise it would probably require a [urllib.quote()](https://docs.python.org/2/library/urllib.html#urllib.quote) to be thrown in there. I ended up using `:/` as the value for the second parameter to the `quote()` method, as the protocol otherwise would be encoded as well.

**Comment by agschwender** [comment]
If you're using the extension example, the url should be: 

`http://127.0.0.1:8888/100x100/http%3A%2F%2Fexample.org%2Ftest%2520image.jpg`

**Comment by Tenzer** [comment]
I actually ended up with something like this wrapper for Pilbox, which means you can just append a URL to the Pilbox service and don't worry about URL encoding it: https://gist.github.com/Tenzer/9b9aaace2b70bce134ae.

With that script you can call `http://127.0.0.1:8888/100x100/http://pilbox-space-test.s3-eu-west-1.amazonaws.com/test image.png` and it will work correctly.
