### ISSUE TITLE
Publish your Dockerfile

### ISSUE THREAD

**Issue by jellybob** [agschwender/pilbox#44]
There's a pilbox repository on Docker hub, but it doesn't include a Dockerfile, and looks to be massively out of date.

Do you still have a copy of the Dockerfile which you used, and if so could you add it here and set up a trusted build so it stays up to date? We're using pilbox in production, but I've got no way of changing the configuration in a repeatable way.

**Comment by agschwender** [comment]
I was formerly maintaining a Dockerfile for Pilbox, but ultimately decided it was out of scope for the project, since there are many ways to manage Pilbox. For example, we use ansible to keep our Pilbox version up-to-date and configurations consistent across our various environments/machines. That said, I'd hoped that someone that was interested in Docker and Pilbox would create a pilbox-docker project and take over management of that.

**Comment by agschwender** [comment]
Here's the last state of it before it was removed from the repo:

https://github.com/agschwender/pilbox/blob/85af102087538f3358e54fbbf2de2e71a54f41e2/Dockerfile

**Comment by agschwender** [comment]
Actually looks like someone did create a repo for this: 

https://github.com/jackphel/pilbox-docker

Though I haven't tested that it's correct or if it's what you're looking for. Suspect it could be beefed up a bit and could benefit from an instructional README.

**Comment by phoet** [comment]
@jellybob i think i tried that out and it worked pretty well

**Comment by jellybob** [comment]
Fair enough - I'd prefer a Dockerfile within the project, if only because we're running a fork to enable Cache-Control headers, but I can see why you'd rather not.

**Comment by agschwender** [comment]
Slightly off topic, but if you didn't want to fork the project in order to set the Cache-Control header, you can just create a custom application that does the following:

```
#!/usr/bin/env python

import tornado.gen

from pilbox.app import PilboxApplication, ImageHandler, \
    start_server, parse_command_line


class CustomApplication(PilboxApplication):
    def get_handlers(self):
        return [(r"/", CustomImageHandler)]


class CustomImageHandler(ImageHandler):
    def prepare(self):
        self.args = self.request.arguments.copy()

    @tornado.gen.coroutine
    def get(self):
        self.validate_request()
        resp = yield self.fetch_image()
        resp.headers["Cache-Control"] = "public, max-age=31536000"
        self.render_image(resp)


if __name__ == "__main__":
    parse_command_line()
    start_server(CustomApplication())
```

**Comment by phoet** [comment]
@agschwender thx for the suggestion, i think i could use that for the animated-gif stuff as well!

**Comment by bounav** [comment]
Just got pilbox working in a docker container today.

Here is my `Dockerfile`, hope it helps others:

```
# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y \
    gcc \
    wget \
    python-numpy \
    python-opencv \
    libjpeg-dev \
    libfreetype6-dev \
    zlib1g-dev \
    libwebp-dev \
    liblcms2-dev
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install pilbox --upgrade
# Show were pilbox is installed
RUN pip show pilbox

# Make port 8888 available to the world outside this container
EXPOSE      8888

# Run app.py when the container launches
ENTRYPOINT ["python"]
CMD ["-m", "pilbox.app", "--max_requests=50", "--timeout=30", "--filter=bicubic", "--format=jpg", "--mode=fill", "--position=center", "--quality=80"]
```

I would be nice to be able to pass the parameters (e.g. `timeout=30`) hardcoded in my docker file to pilbox at runtime... but I don't know how to do that.
