### ISSUE TITLE
Request: Handle error codes and messages in custom application

### ISSUE THREAD

**Issue by xtagon** [agschwender/pilbox#46]
Hi,

I have an application inheriting PilboxApplication. Is there a way I can write a handler that will run my own custom action when a Pilbox error happens, and give me the Pilbox code and error message? I would like the normal logging to still occur, but I want to additionally post it to our exception handling service.

What would be the best way for me to get each error when they occur? Is there a way to do this without forking Pilbox? Can I get the error code, error message, and the original request info?

Thanks,
Justin

**Comment by xtagon** [comment]
Figured it out. It's easy to override `write_error()` and call `super()`.

**Comment by agschwender** [comment]
If only all reported issues were this easy... Glad you figured it out.
