### ISSUE TITLE
Images with %20 in their name

### ISSUE THREAD

**Issue by JamesIves** [agschwender/pilbox#49]
I'm attempting to use Pilbox on some images that have %20 in their name to substitute a white space. What I'm running into is that the image works when it's loaded directly but when it's ran through the resizer it refuses to work. I have other images that are pumped in through the same API which do work, but those don't have %20 in their name. 

Is there some sort of trick or work around to getting this to work? Changing the file name is not an option as I'm working with a large amount of imported data.

The message I get:
```{"error":"not found"}```

This image works: http://www.adn.com/sites/default/files/styles/ad_slideshow_940/public/Glacier-150831-13.JPG
This image does not: http://www.adn.com/sites/default/files/styles/ad_slideshow_940/public/helio%20sequence%20horiz.jpg

**Comment by agschwender** [comment]
Are you sure you are url encoding it correctly?  When it's passed to pilbox it needs to be urlencoded like so:

```http%3A%2F%2Fwww.adn.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fad_slideshow_940%2Fpublic%2Fhelio%2520sequence%2520horiz.jpg```

**Comment by JamesIves** [comment]
Appears that this was my issue! Thanks so much.
