### ISSUE TITLE
Limit max value for resize `h` and `w`

### ISSUE THREAD

**Issue by inoks** [agschwender/pilbox#52]
Since there no any limits applied, there possibility for some kind of DDoS attack, if someone decide to set pretty big value for h/w (for example if they set it to `sys.maxint` which is 9223372036854775807 for Python2).

**Comment by agschwender** [comment]
The most reliable way to avoid this is to require signed urls which can be enabled by specifying a `client_key` in your configuration. 

That said, upscaling doesn't generally make sense, so will add some sensical defaults for max width and height.

**Comment by agschwender** [comment]
Resolved in efe2cbec9eb26a8b8c2398e0f115b693cb932024
