### ISSUE TITLE
proportional  resize 

### ISSUE THREAD

**Issue by RajeshDhalange** [agschwender/pilbox#62]
can I resize image proportional to the width or height by not specifying width or height?

**Comment by agschwender** [comment]
Yes, from [the Calling section of the README](https://github.com/agschwender/pilbox#calling):

```
For resizing, either the w or h parameter is required. If only one dimension is specified, the application will determine the other dimension using the aspect ratio.
```

**Comment by RajeshDhalange** [comment]
thank you for the response it's working,
