### ISSUE TITLE
3 tests failing

### ISSUE THREAD

**Issue by murbans1** [agschwender/pilbox#65]
Hi,

I have started pillbox on vagrant and run tests. 3 of them fail. They have issues with webp files. 

`======================================================================
FAIL: test_valid (pilbox.test.app_test.AppRestrictedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/testing.py", line 136, in __call__
    result = self.orig_method(*args, **kwargs)
  File "pilbox/test/app_test.py", line 579, in test_valid
    self.assertEqual(resp.buffer.read(), expected.read(), msg)
AssertionError: /?url=http%3A%2F%2Flocalhost%3A46410%2Ftest%2Fdata%2Ftest4.webp&h=300&client=abc&mode=adapt&w=300&sig=3e789c4ae9a341eb8a6dc0805317fe4d809d8df6 does not match pilbox/test/data/expected/test4-300x300-mode=adapt.webp

======================================================================
FAIL: test_valid_resize (pilbox.test.app_test.AppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/testing.py", line 136, in __call__
    result = self.orig_method(*args, **kwargs)
  File "pilbox/test/app_test.py", line 365, in test_valid_resize
    self._assert_expected_case(case)
  File "pilbox/test/app_test.py", line 403, in _assert_expected_case
    self.assertEqual(resp.buffer.read(), expected.read(), msg)
AssertionError: /?url=http%3A%2F%2Flocalhost%3A40399%2Ftest%2Fdata%2Ftest4.webp&h=300&mode=adapt&w=300 does not match pilbox/test/data/expected/test4-300x300-mode=adapt.webp

======================================================================
FAIL: test_resize (pilbox.test.image_test.ImageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pilbox/test/image_test.py", line 145, in test_resize
    self._assert_expected_resize(case)
  File "pilbox/test/image_test.py", line 343, in _assert_expected_resize
    self.assertEqual(rv.read(), expected.read(), msg)
AssertionError: pilbox/test/data/test4.webp does not match pilbox/test/data/expected/test4-300x300-mode=adapt.webp

----------------------------------------------------------------------
Ran 91 tests in 9.341s

FAILED (failures=3)
[E 171212 12:26:12 testing:737] FAIL
`
Do I need to install something more to make these tests pass?

Cheers,
Maciek

**Comment by agschwender** [comment]
Regenerated the webp files. Guessing there was an update to the webp libraries that caused its output to change since I didn't pin those versions in the vagrant playbook. If you pull, you should be able to the tests successfully.

**Comment by murbans1** [comment]
All tests pass now. Thank You :)
