### ISSUE TITLE
how to cache original image

### ISSUE THREAD

**Issue by kenziedika** [agschwender/pilbox#72]
how to set pilbox to cache original image?
because i'm need when new request resize on same image origin don't to download again from origin.

**Comment by agschwender** [comment]
Typically you run with a CDN in front of pilbox so it caches each resize. If you want to cache the source, you can do that by calling the source through CDN, either by having the caller make each URL the URL on the CDN or by extended pilbox to alter the supplied URL to go through a CDN. Pilbox itself does no caching directly.
